# Settings


# Categorization schema

# Classification categories
MASTER_CATEGORIES = ["Billing", "Technical", "Account", "Feedback", "Other"]
# Classification priorities
MASTER_PRIORITIES = ["High", "Medium", "Low"]
# Labels for new columns to be added 
MASTER_COLUMNS = ["ai_category", "ai_priority", "ai_certainty", "ai_certainty_reason"]
# Fallback values for new columns in case of failure
MASTER_COLUMNS_FALLBACK = ["Error", "Error", 0.0, "N/A"]


# Structured output schema (JSON enforcement)
# We use a strict JSON schema to ensure Gemini's output is machine-readable.
# We leverage 'enum' to force the AI to use our pre-defined categories/priorities,
# ensuring consistent data for our later analysis and dashboard.
CLASSIFICATION_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        MASTER_COLUMNS[0]: {
            "type": "STRING", 
            "enum": MASTER_CATEGORIES 
        },
        MASTER_COLUMNS[1]: {
            "type": "STRING",
            "enum": MASTER_PRIORITIES,
            "description": "High: Critical failure/Financial loss. Medium: Broken feature with workaround. Low: General questions."
        },
        MASTER_COLUMNS[2]: {
            "type": "NUMBER",
            "minimum": 0,
            "maximum": 1,
            "description": "A score from 0.0 to 1.0 representing classification confidence."
        },
        MASTER_COLUMNS[3]: {
            "type": "STRING",
            "description": "Brief explanation of why this certainty score was given."
        }
    },
    "required": MASTER_COLUMNS
}


# File paths/names

OUTPUT_DIR = "data"
# Default support tickets file to be used
INPUT_FILE = f"{OUTPUT_DIR}/tickets-10.csv"
# Default file name generated by create_tickets.py
TEST_FILE = f"{OUTPUT_DIR}/tickets-test.csv"
# Default enriched tickets file generated by classifier.py
OUTPUT_FILE = f"{OUTPUT_DIR}/enriched_tickets.csv"
# Default statistics file generated by analyst.py
STATS_FILE = f"{OUTPUT_DIR}/statistics.csv"


# AI logic

# Model alias to be used
MODEL_NAME = "gemini-flash-latest"
# Wait time in seconds between ticket classifications (helps stay under rate limits)
WAIT_TIME = 1
# Value below which responses are deemed unreliable
CONFIDENCE_THRESHOLD = 0.85
# Formatting of tickets generated by create_tickets.py
TICKET_CREATOR_COLUMNS = ["ticket_id", "customer_name", "issue_description"]